title: "Dr. Ting Lu"
author: "Ting Lu"
email: "tinglu2024@gmail.com"
description: "Lecturer in Faculty of Maritime and Transportation, Ningbo University. Research interests: Traffic Flow Theory, Traffic management."
baseurl: ""
url: "https://tinglu2024.github.io"
github_username: "tinglu2024"

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
