title: Dr.
author: Ting Lu
email: tinglu2024@gmail.com
description: Lecturer in Faculty of Maritime and Transportation, Ningbo University.
Research interests: Traffic Flow Theory, Traffic management.
baseurl: "/academicons"
url: "https://tinglu.github.io"
github_username:  tinglu2024

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
